org: surendrakumar
service: audio-scribe

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "lambda:GetFunction"
      Resource: "*"

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"


plugins:
  - serverless-offline


custom:
  serverless-offline:
    httpPort: 4000
